### ISSUE TITLE
Need help: Set ServerOptions

### ISSUE THREAD

**Issue by Ferdyverse** [Programmer-Timmy/satisfactory-dedicated-server-api-SDK#8]
Hello, can you pls give me a hint on how I can set the server options? I can not get it to work. Do I have to set all options each time or can I just send one change?

Thank you

**Comment by Programmer-Timmy** [comment]
I see you closed it. If you think the Readme should be improved. You're free to open a pull request.

Ps you indeed need to send al the options. You can make something that gets the settings and then use that.

I also see that Readme is not up to date with the new dataclass I added. I will look into that. I will reopen this issue.

**Comment by Programmer-Timmy** [comment]
I have found a bug on my end. Sorry about that. Im fixing it right now and wil update it soon! Thanks for your issue. Also it seems like you dont have to give all the options. Also applying that right now to the dataClass

**Comment by Programmer-Timmy** [comment]
This is now fixed! If you find anything else please let me know!

**Comment by Ferdyverse** [comment]
For me it is still not working: `Could not change setting: Unexpected err=AttributeError("'dict' object has no attribute 'to_dict'"), type(err)=<class 'AttributeError'>`

```python
setting = "DSAutoPause"
value = False

api.apply_server_options({setting: value})
```

I fixed it by adding `from .server_options import ServerOptions` into the date-init-file. The I could Import it like `from satisfactory_api_client.data import ServerOptions` and use it:

```python
new_setting = ServerOptions()
setattr(new_setting, setting, value)
api.apply_server_options(new_setting)
```

**Comment by Programmer-Timmy** [comment]
The new version is out now! Thanks for your help.
